vich_uploader:
    db_driver: orm

    mappings:
        pp:
            uri_prefix: /images/pp
            upload_destination: '%kernel.project_dir%/public/images/pp'
            namer: Vich\UploaderBundle\Naming\UniqidNamer